Repository domharrington/node-gitlog, pull requests merged in 2020-04, with the labels that each got.

#45 Modernize Dev Tooling
  .editorconfig
  .eslintrc
  .gitignore
  .jscsrc
  .jshintignore
  .jshintrc
  README.md
  example/example.js
  index.js
  package-lock.json
  package.json
  src/index.js
  test/gitlog.test.js
Labels: internal

#46 rewrite in TypeScript
  .eslintrc
  .gitignore
  README.md
  package-lock.json
  package.json
  src/index.js
  src/index.ts
  test/gitlog.test.js
  test/gitlog.test.ts
  tsconfig.json
Labels: minor

#47 Automate release
  .all-contributorsrc
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: internal

#48 fix files type
  src/index.ts
Labels: patch

#49 Update index.ts
  src/index.ts
Labels: patch

#51 Easier to use option type
  README.md
  src/index.ts
Labels: patch

#53 update readme to fix cjs usage
  README.md
Labels: major
